config/routes.rb
SetupApp::Application.routes.draw do
  resources :users

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup', :to =>  'users#new'
  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
# Schema version: 20110608143704
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true
  validates :name, :length   => { :maximum => 50 }

  validates :email, :presence => true
  validates :email, :format => { :with => email_regex }
  validates :email, :uniqueness => { :case_sensitive => false }

  validates :password, :presence => true
  validates :password, :confirmation => true
  validates :password, :length => { :within => 5..20 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  private

  def encrypt_password
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    string
  end

  def self.authenticate(submitted_email, submitted_password)
    user = find_by_email(submitted_email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @title = "Sign Up"
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def create
    @user = User.new(params[:user])
      if @user.save
        redirect_to @user
      else
        @title = "Sign Up"
        render 'new'
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Return a title on a per-page basis

def title
  base_title = "Ruby on Rails Tutorial"
  if @title.nil?
    base_title
  else
    "#{base_title} | #{@title}"
  end
end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = {:size => 50 })
      gravatar_image_tag(user.email.downcase, :alt => user.name, :class => 'gravatar', :gravatar => options)
  end

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.cnn.com">News</a></li>
      <li><a href="http://www.linkedin.com/pub/ashish-dua/19/a6a/165">Ashish Dua</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<% logo = image_tag("logo.png", :alt => "Sample App", :class => "round") %>
<%= link_to logo, root_path %>

  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Sign in", '#' %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'screen', :media => 'screen' %>
<%= stylesheet_link_tag 'print',  :media => 'print' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title><%= title %></title>
        <%= csrf_meta_tag %>
        <%= render 'layouts/stylesheets' %>
 </head>
  <body>
    <div class="container">
        <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      <%= yield %>
      </section>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>  
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
  <p> Cave Johnson founded the company in 1953 for the sole purpose of making shower curtains for the U.S. military. However, after becoming mentally unstable from mercury poisoning in 1978, Johnson created a three-tier research and development plan to make his organization successful. The first two tiers, the Counter-Heimlich Maneuver (a maneuver designed to ensure choking) and the Take-A-Wish Foundation (a program to give the wishes of dying children to unrelated, entirely healthy adults), were commercial failures and led to an investigation of the company by the U.S. Senate. However, when the investigative committee heard of the success of the third tier, a man-sized ad-hoc quantum tunnel through physical space with possible applications as a shower curtain, it recessed permanently and gave Aperture Science an open-ended contract to continue its research. The development of GLaDOS, an artificially intelligent research assistant and disk-operating system, began in 1986 in response to Black Mesa's work on similar portal technology.
    <a href="http://en.wikipedia.org/wiki/Portal_(video_game)#Setting">More Information</a>
  </p>

app/views/pages/contact.html.erb
<h1>Sample App</h1>
<p>
  This is the home page for the 
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
</p>

app/views/pages/help.html.erb
<h1>Help</h1>

app/views/pages/home.html.erb
<h1>Aperture</h1>
<p>
   This is the home page for the
  <a href="http://www.aperturescience.com/">Aperture Laboratories</a>
</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>